# Change these first
owner: cxt666 # Your GitHub organization or username, where this repository lives
repo: suras # The name of this repository

sites:
  - name: SURAS-DE
    url: https://de-emea-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-DE 2
    url: https://de-emea2-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-DE 3
    url: https://de-emea3-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-AP
    url: https://kr-ap-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-CN
    url: https://cn-ap-vpn.schaefflercn.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-IN
    url: https://in-ap-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-NA 1
    url: https://us-equ1-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-NA 2
    url: https://us-na2-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-BR
    url: https://br-sa-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /suras
  logoUrl: https://de-emea-vpn.schaeffler.com/dana-na/auth/url_F0ZNbTAu5fADsXG8/welcome.cgi?p=logo&signinId=url_F0ZNbTAu5fADsXG8 #https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SURAS Monitoring
  favicon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  introTitle: Monitoring SURAS Gateways
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  theme: dark # light, dark, ocean
  robotsText: "User-agent: * \n Disallow: /"
  user-agent: cxt666
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/cxt666/suras

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
